### PR TITLE
notifications of connection drops

### PR DESCRIPTION
**Pull request by ryansgot**
Especially in the absence of a UUID for tracking payments and querying the clover mini about the status of payments, some connection monitoring is required. The motivation for the connection monitor is to avoid, via cancellation, inconsistent payment state between the two devices (disconnections can happen at any time) and also connectivity robustness.

It looks like reconnection mechanisms are already in place, so all I had to do was implement the heartbeat.

It looks like there is a potential for concurrency problems with the assignments in the `onClose` callback, however, it is also possible that the blocking close (in the disconnector) negates the risk of leaving the `webSocket` unprotected. My testing has not revealed any problems.

### CODE REVIEW

**Comment by ryansgot** [comment]
I'm thinking that immediately disconnecting when a heartbeat interval is missed, although it appears to work just fine, may be a little heavy-handed. So I'm working on an alternative solution that has a retry-counter.

**Comment by mckinleymax** [comment]
@ryansgot Let us know when this has been updated so we can review

**Comment by ryansgot** [comment]
@mckinleymax This is the updated PR.

**Comment by blake-clover** [comment]
Is there a use case where onDisconnecting does something different than onDisconnected? Is this so the client will not initiate a new connection (i.e. new CloverConnector) for Disconnecting but might for Disconnected?

**Comment by ryansgot** [comment]
@blake-clover onDisconnecting is intended as an intermediate state between the time that we detect there is possibly a connection issue and when we actually disconnect. This will allow any observers to take appropriate behavior (give up on taking payment via the clover, for example) at the same time as the WebSocketCloverTransport allows a little more time for a pong message to come back.

I added this state because it keeps the transport from disposing of the connection at the first instance of a late pong message, which, in my testing, I found was somewhat common with relatively low keepalive times. So it's like an early warning system.

**Comment by duane1024** [comment]
Incorporated into latest 0.4 release

**Pull request closed without merging**
